version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
