spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_URL}/booking-center
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    security:
      protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: booking-center

topic:
  geo: ${spring.profiles.active}-texi-geo-topic

logging:
  level:
    com.keabank: ${LOG_LEVEL:info}

server:
  error:
    include-message: always
    include-exception: true